### ISSUE TITLE
What is the article corresponding to the code?

### ISSUE THREAD

**Issue by tianlexm** [axel-fehr/minimizing-electricity-cost-with-model-based-deep-RL#1]
What is the article corresponding to the code?

**Comment by ax-fe** [comment]
I wrote a thesis on this topic but it is unfortunately not publicly available. However, the implemented method is based on model-based reinforcement learning with Bayesian neural networks as introduced by Depeweg et al. in the paper _"Learning and policy search in stochastic dynamical systems with Bayesian neural networks"_ . I applied the method described in there to optimize the electricity cost.

Link to the paper: https://arxiv.org/abs/1605.07127

I hope this helps.
